### PR TITLE
handle falldamage on mounted players

### PR DESCRIPTION
**Pull request by Boy0000**
Currently itll not apply damage aslong as the entity isnt set to die from the event.
If the entity dies the remaining damage is applied to all passengers and drivers.

Feels like a semi-good reason to use mounted mobs above just speed

### CODE REVIEW

**Review by 0ffz — CHANGES_REQUESTED** [review]
Idk if this makes sense to be in mobzy, it's a vanilla feature we're overriding and bonehurt seems to be the place we're already changing that feature. This doesn't utilize anything in mobzy so I think it's safe to move.

**Comment by Boy0000** [comment]
In vanilla riding mobs of of cliffs dont bypass falldamage. Only specific entities like boats cause no falldamage
Basically wanted to replicate how its like riding a horse or pig of a cliff here

**Comment by 0ffz** [comment]
If vanilla mobs do the damage, how come ours dont?

**Comment by Boy0000** [comment]
> If vanilla mobs do the damage, how come ours dont?

because theyre not entities in the same way. ur free to try if u dont believe they do but

**Comment by Boy0000** [comment]
the entity itself takes damage, but it doesnt translate to the mounted ones. Gonna merge this as theres no reason not to.
Entity thats being ridden isnt touched by this, this is just to translate remaining damage when said entity dies over to passengers of it

**Pull request merged**
